version: "3"

services:
  cp-app:
    build:
      context: .
      dockerfile: Dockerfile-php-apache
    container_name: cp_app
    ports:
      - "8889:80"
    volumes:
      - ../:/var/www/html
    networks:
     - cp

  cp-app-cli:
    build:
      context: .
      dockerfile: Dockerfile-php-cli
    container_name: cp_app_cli
    working_dir: /app
    volumes:
      - ../:/app
    networks:
     - cp

  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    networks:
    - cp

networks:
 cp: