version: "3"

services:
  cp-app:
    build:
      context: .
      dockerfile: Dockerfile-php-apache
    networks:
     - cp

  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=root
    networks:
    - cp

networks:
 cp: